name: codiff
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-image
  - pillow
  - opencv
  - pytorch
  - torchvision
  - pip:
      - diffusers==0.28.1
      - huggingface-hub==0.13.4
      - pyiqa==0.1.13
      - torchmetrics==1.7.0
      - pytorch-lightning==2.3.0
      - basicsr==1.4.2
      - timm==1.0.14
      - open-clip-torch==2.20.0
      - transformers==4.37.2
      - safetensors==0.5.2
      - einops==0.8.1
      - lpips==0.1.4
      - vector-quantize-pytorch==1.22.3
      - accelerate==1.3.0
      - bitsandbytes==0.45.0
      - wandb==0.19.4
      - xformers==0.0.20